# Generated by Django 4.2.5 on 2023-09-28 04:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_fields', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(default='', max_length=350)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'PENDING'), (1, 'IN_PROGRESS'), (2, 'COMPLETED')], default=0)),
            ],
            options={
                'verbose_name_plural': 'tasks',
            },
        ),
    ]
